### ISSUE TITLE
Madagascar (MG) joined iban

### ISSUE THREAD

**Issue by aiacciu** [shouze/php-iban#1]
Hello,
As Madagascar (and perhaps other countries) joined then iban since 2012, could you please add it to the txt file?

Thank you

**Comment by globalcitizen** [comment]
Hi there. This project is just a mirror of our Google Code hosted project before it moved to Github and is very out of date ... you can find the up to date version at https://github.com/globalcitizen/php-iban  ... however it doesn't include Madagascar, because it's not in the official SWIFT-published IBAN registry.

If you can find a statement regarding the MG IBAN prefix from an official source in Madagascar, please  open an issue at https://github.com/globalcitizen/php-iban/issues/new and I will add it.

In the mean time I note that it is in the list of unofficial IBANs published at https://en.wikipedia.org/wiki/International_Bank_Account_Number .. I will integrate these in to the project shortly.

**Comment by shouze** [comment]
Hi @aiacciu... so sorry I didn't see your issue at all... apologies.

@globalcitizen oops yes ok you are at the origin of the project indeed and I mirrored your project I will add a notice in a README file to fix that.

**Comment by globalcitizen** [comment]
Thanks much appreciated.
