### ISSUE TITLE
Confused users

### ISSUE THREAD

**Issue by globalcitizen** [shouze/php-iban#2]
Would you be so kind as to either remove the project or add a README.md notice regarding the new location of the project on Github? We're now at https://github.com/globalcitizen/php-iban 

I only ask because I noticed from the other issue that there are confused users arriving here as late as the end of 2014. Thanks.

**Comment by shouze** [comment]
@globalcitizen Hello, ok I didn't know you've made a fork (in fact it's not a github fork, why did you create another repository from scratch instead of making a fork?).

So... ok as it seems you've made so much work on it I add a README file pointing out to your repo and sayin this one is deprecated ;)

**Comment by globalcitizen** [comment]
Thanks much appreciated.
